var Protein, Fat, Calories, Carbs, WhichToRemove, OldQuantity, Update;
Protein = Fat = Calories = Carbs = WhichToRemove = OldQuantity = Update = 0;
InstanceOfExpander = new Expander();
InstanceOfSelect2Options = new Select2Options();
InstanceOfAdderReferencer = new AdderReferencer();
InstanceOfLocker = new Locker();
InstanceOfHistoryOverwriter = new HistoryOverwriter();
InstanceOfOptionExister = new OptionExister();
InstanceOfOperatorSwitcher = new OperatorSwitcher();
InstanceOfHistoryRemover = new HistoryRemover();
InstanceOfElementRemover = new ElementRemover();
