     <script src="js/ingredients.js"></script>
     <script src="js/file_proceder.js"></script>
     <script src="js/requester.js"></script>
     <script src="js/history_last_element.js"></script>
     <script src="js/history_element.js"></script>
     <script src="js/element_remover.js"></script>
     <script src="js/history_remover.js"></script>
     <script src="js/operator_switcher.js"></script>
     <script src="js/option_exister.js"></script>
     <script src="js/history_overwriter.js"></script>
     <script src="js/history_initializer.js"></script>
     <script src="js/history_keeper.js"></script>
     <script src="js/adder_referencer.js"></script>
     <script src="js/result_updater.js"></script>
     <script src="js/quantity_returner.js"></script>
     <script src="js/key_geter.js"></script>
     <script src="js/blank_option_keeper.js"></script>
     <script src="js/clear_select2_options.js"></script>
     <script src="js/lock_swicher.js"></script>
     <script src="js/current_state_of_expander.js"></script>
     <script src="js/expander.js"></script>
     <script src="js/smart_choice.js"></script>
     <script src ="js/data_base.js"></script>
     <script src="js/locker.js"></script>
     <script src="js/select2_options.js"></script>
     <script src="js/adder.js"></script>
     <script src="js/main.js"></script>
     <link rel="stylesheet" type="text/css" href="css/main.css">
